# Generated by Django 3.0.3 on 2020-08-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(max_length=12)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.CharField(max_length=64)),
                ('card_number', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=64)),
            ],
        ),
    ]
