# Generated by Django 3.0.3 on 2020-08-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='authorization_code',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='logs',
            name='message',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
